### ISSUE TITLE
Add Health Check for Alloy Container in observability/compose.yaml

### ISSUE THREAD

**Issue by ranzyblessings** [ranzyblessings/roi-project-planner#16]
#### **Problem:**

The official **Alloy** image lacks tools like `nc`, `wget`, or `curl`, preventing us from implementing a health check. This limits our ability to verify the container’s operational status.

#### **Proposed Solution:**

We have two options:
1. Extend the official **Alloy** image with a custom `Dockerfile` that includes `nc`, `wget`, or `curl`.
2. Contact the Alloy team to request the inclusion of these utilities in the base image.

Once the required tools are available, we can implement a health check to ensure the container is healthy before being considered operational.

#### **Example Health Check:**

```yaml
  alloy:
    image: 'grafana/alloy:v1.6.1'
    container_name: 'alloy'
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ../logs/application.log:/var/log/application.log
    networks:
      - observability-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:12345/metrics" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    depends_on:
      loki:
        condition: service_healthy
```

#### References:
[Grafana Alloy Documentation](https://grafana.com/docs/alloy/latest/get-started)
[Docker Compose Health Check Documentation](https://docs.docker.com/reference/compose-file/services/#healthcheck)
